In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import olympus
from olympus.datasets import Dataset
from olympus.evaluators import Evaluator
from olympus.emulators import Emulator
from olympus.campaigns import Campaign
from olympus.planners import Planner
from olympus.scalarizers import Scalarizer

## CASE STUDY 1

In [3]:
cs1_datasets = ['dye_lasers']
cs1_planners = [
    #'RandomSearch', 
    'Genetic',
    #'Hyperopt', 
    #'Gpyopt', 
    #'Gryffin', 
    #'Dragonfly', 
    #'Botorch',
    #'Smac',
    #'Hebo',
]  

In [4]:
for dataset_name in cs1_datasets:
    for planner_name in cs1_planners:
        
        print(f'\nTESTING {planner_name} ON {dataset_name} ...\n')
            
        if dataset_name == 'dye_lasers':
            # fully categorical, lookup table
            dataset = Dataset(kind=dataset_name)

            planner = Planner(kind=planner_name)
            planner.set_param_space(dataset.param_space)

            campaign = Campaign()
            campaign.set_param_space(dataset.param_space)
            campaign.set_value_space(dataset.value_space)
            
            scalarizer = Scalarizer(
                kind='Chimera', 
                value_space=dataset.value_space,
                goals=['max', 'min', 'max'],
                tolerances=[0.5, 0.5, 0.5],
                absolutes=[False, False, False]
            )

            evaluator = Evaluator(
                planner=planner, 
                emulator=dataset,
                campaign=campaign,
                scalarizer=scalarizer,
            )
        
        elif dataset_name == 'redoxmers':
            # fully categorical, lookup table
            dataset = Dataset(kind=dataset_name)

            planner = Planner(kind=planner_name)
            planner.set_param_space(dataset.param_space)

            campaign = Campaign()
            campaign.set_param_space(dataset.param_space)
            campaign.set_value_space(dataset.value_space)
            
            scalarizer = Scalarizer(
                kind='Chimera', 
                value_space=dataset.value_space,
                goals=['min', 'min', 'min'],
                tolerances=[0.5, 0.5, 0.5],
                absolutes=[False, False, False]
            )

            evaluator = Evaluator(
                planner=planner, 
                emulator=dataset,
                campaign=campaign,
                scalarizer=scalarizer,
            )
            
        evaluator.optimize(num_iter=15)
        
        print('Done!')


TESTING Genetic ON dye_lasers ...



TypeError: 'Individual' object cannot be interpreted as an integer

In [ ]:
campaign.observations.get_params()
campaign.observations.get_values()

In [ ]:
campaign.scalarized_observations.get_values()

## CASE STUDY 2 

In [5]:
#----------------
# SUZUKI MIYAURA
#----------------

#suzuki_datasets = ['suzuki', 'suzuki_i', 'suzuki_ii', 'suzuki_iii', 'suzuki_iv', 'suzuki_edbo']
suzuki_datasets = ['suzuki_i', 'suzuki_ii', 'suzuki_iii', 'suzuki_iv'] #['suzuki_edbo']

suzuki_planners = [
    #'RandomSearch', 
    'Genetic',
    #'Hyperopt', 
    #'Gpyopt', 
    #'Gryffin', 
    #'Dragonfly', 
    #'Botorch',
    #'Smac',
    #'Hebo',
]  
#suzuki_planners = ['RandomSearch']

In [6]:
for dataset_name in suzuki_datasets:
    for planner_name in suzuki_planners:
        
        print(f'\nTESTING {planner_name} ON {dataset_name} ...\n')
        
        if dataset_name == 'suzuki': 
            
            # fully continuous, emulated dataset
            emulator = Emulator(dataset=dataset_name, model='BayesNeuralNet')
            planner = Planner(kind=planner_name)
            planner.set_param_space(emulator.param_space)

            campaign = Campaign()
            campaign.set_param_space(emulator.param_space)
            campaign.set_value_space(emulator.value_space)

            evaluator = Evaluator(
                planner=planner, 
                emulator=emulator,
                campaign=campaign,
            )
            
        elif dataset_name == 'suzuki_edbo':
            
            # fully categorical, lookup table
            dataset = Dataset(kind=dataset_name)

            planner = Planner(kind=planner_name)
            planner.set_param_space(dataset.param_space)

            campaign = Campaign()
            campaign.set_param_space(dataset.param_space)
            campaign.set_value_space(dataset.value_space)

            evaluator = Evaluator(
                planner=planner, 
                emulator=dataset,
                campaign=campaign,
            )
            
        elif dataset_name in ['suzuki_i', 'suzuki_ii', 'suzuki_iii', 'suzuki_iv']:
            
            # mixed parameter, emulator, multi-objective optimization
            emulator = Emulator(dataset=dataset_name, model='BayesNeuralNet')
            planner = Planner(kind=planner_name)
            planner.set_param_space(emulator.param_space)

            campaign = Campaign()
            campaign.set_param_space(emulator.param_space)
            campaign.set_value_space(emulator.value_space)
            
            scalarizer = Scalarizer(
                kind='Chimera', 
                value_space=emulator.value_space,
                goals=['max', 'max'],
                tolerances=[0.9, 0.0],
                absolutes=[False, False]
            )

            evaluator = Evaluator(
                planner=planner, 
                emulator=emulator,
                campaign=campaign,
                scalarizer=scalarizer,
            )
        
        evaluator.optimize(num_iter=10)
        
        print('Done!')


TESTING Genetic ON suzuki_i ...

[INFO] Loading emulator using a BayesNeuralNet model for the dataset suzuki_i...


/home/riley/Software/anaconda3/envs/olympus/lib/python3.7/site-packages/tensorflow_probability/python/layers/util.py:102: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  trainable=trainable)
/home/riley/Software/anaconda3/envs/olympus/lib/python3.7/site-packages/tensorflow_probability/python/layers/util.py:112: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  trainable=trainable)


Done!

TESTING Genetic ON suzuki_ii ...

[INFO] Loading emulator using a BayesNeuralNet model for the dataset suzuki_ii...
Done!

TESTING Genetic ON suzuki_iii ...

[INFO] Loading emulator using a BayesNeuralNet model for the dataset suzuki_iii...
Done!

TESTING Genetic ON suzuki_iv ...

[INFO] Loading emulator using a BayesNeuralNet model for the dataset suzuki_iv...
Done!


In [ ]:
campaign.observations.get_values()

In [7]:
#------------------
# BUCHWALD-HARTWIG
#------------------

buchwald_datasets = ['buchwald_a','buchwald_b','buchwald_c','buchwald_d','buchwald_e']

buchwald_planners = [
    #'RandomSearch', 
    'Genetic',
    #'Hyperopt', 
    #'Gpyopt', 
    #'Gryffin', 
    #'Dragonfly', 
    #'Botorch',
    #'Smac',
    #'Hebo',
] 


In [8]:
buchwald_campaigns = []

for dataset_name in buchwald_datasets:
    for planner_name in buchwald_planners:
        
        print(f'\nTESTING {planner_name} ON {dataset_name} ...\n')
        
        dataset = Dataset(kind=dataset_name)
        planner = Planner(kind=planner_name)
        planner.set_param_space(dataset.param_space)
        
        campaign = Campaign()
        campaign.set_param_space(dataset.param_space)
        campaign.set_value_space(dataset.value_space)
        
        evaluator = Evaluator(
            planner=planner, 
            emulator=dataset,
            campaign=campaign,
        )
        
        evaluator.optimize(num_iter=15)
        
        print('Done!')
        
        buchwald_campaigns.append(campaign)


TESTING Genetic ON buchwald_a ...



TypeError: 'Individual' object cannot be interpreted as an integer

## CASE STUDY 3

In [40]:
cs3_datasets = ['dye_lasers'] #'redoxmers']
cs3_planners = [
    #'RandomSearch', 
    #'Genetic',
    #'Hyperopt', 
    #'Gpyopt', 
    #'Gryffin', 
    #'Dragonfly', 
    'Botorch',
    #'Smac',
    #'Hebo',
] 
cs3_scalarizers = ['Chimera', 'WeightedSum', 'Parego'] # 'ConstrainedAsf'

In [41]:
for dataset_name in cs3_datasets:
    for planner_name in cs3_planners:
        for scalarizer_name in cs3_scalarizers:
        
            print(f'\nTESTING {planner_name} ON {dataset_name} WITH {scalarizer_name} ...\n')

            if dataset_name == 'dye_lasers':
                # fully categorical, lookup table
                dataset = Dataset(kind=dataset_name)

                planner = Planner(kind=planner_name)
                planner.set_param_space(dataset.param_space)

                campaign = Campaign()
                campaign.set_param_space(dataset.param_space)
                campaign.set_value_space(dataset.value_space)

                if scalarizer_name == 'Chimera':
                    scalarizer = Scalarizer(
                        kind='Chimera', 
                        value_space=dataset.value_space,
                        goals=['max', 'min', 'max'],
                        tolerances=[0.5, 0.5, 0.5],
                        absolutes=[False, False, False]
                    )
                elif scalarizer_name == 'Parego':
                    scalarizer = Scalarizer(
                        kind='Parego', 
                        value_space=dataset.value_space,
                        goals=['max', 'min', 'max'],
                        rho=0.05,
                    )
                
                elif scalarizer_name == 'WeightedSum':
                    scalarizer = Scalarizer(
                        kind='WeightedSum', 
                        value_space=dataset.value_space,
                        goals=['max', 'min', 'max'],
                        weights=[0.33, 0.33, 0.33],
                    )
                
                elif scalarizer_name == 'ConstrainedAsf':
                    pass
                    # TODO: implement this! 
                    

                evaluator = Evaluator(
                    planner=planner, 
                    emulator=dataset,
                    campaign=campaign,
                    scalarizer=scalarizer,
                )

            elif dataset_name == 'redoxmers':
                # fully categorical, lookup table
                dataset = Dataset(kind=dataset_name)

                planner = Planner(kind=planner_name)
                planner.set_param_space(dataset.param_space)

                campaign = Campaign()
                campaign.set_param_space(dataset.param_space)
                campaign.set_value_space(dataset.value_space)

                if scalarizer_name == 'Chimera':
                    scalarizer = Scalarizer(
                        kind='Chimera', 
                        value_space=dataset.value_space,
                        goals=['min', 'min', 'min'],
                        tolerances=[0.5, 0.5, 0.5],
                        absolutes=[False, False, False]
                    )
                elif scalarizer_name == 'Parego':
                    scalarizer = Scalarizer(
                        kind='Parego', 
                        value_space=dataset.value_space,
                        goals=['min', 'min', 'min'],
                        rho=0.05,
                    )
                
                elif scalarizer_name == 'WeightedSum':
                    scalarizer = Scalarizer(
                        kind='WeightedSum', 
                        value_space=dataset.value_space,
                        goals=['min', 'min', 'min'],
                        weights=[0.33, 0.33, 0.33],
                    )
                
                elif scalarizer_name == 'ConstrainedAsf':
                    pass
                    # TODO: implement this! 

                evaluator = Evaluator(
                    planner=planner, 
                    emulator=dataset,
                    campaign=campaign,
                    scalarizer=scalarizer,
                )

            evaluator.optimize(num_iter=15)

            print('Done!')


TESTING Botorch ON dye_lasers WITH Chimera ...

False
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], dtype=torch.float64)
False
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], dtype=torch.float64)
False
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], dtype=torch.float64)
False
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  

False
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], dtype=torch.float64)
Done!
