In [110]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [111]:
import numpy as np
from olympus import Dataset

In [112]:
dataset = Dataset(kind='perovskites')
print(dataset.data.shape, dataset.data.columns)
dataset.data.head()

(192, 4) Index(['organic', 'cation', 'anion', 'hse_gap'], dtype='object')


organic cation anion hse_gap
0  ethylammonium     Ge     F  5.3704
1  ethylammonium     Ge    Cl  3.1393
2  ethylammonium     Ge    Br  2.7138
3  ethylammonium     Ge     I  2.2338
4  ethylammonium     Sn     F  3.9789

In [113]:
print(dataset.goal)
print(dataset.measurement_name)
print(dataset.size)
print(dataset.shape)
#print(dataset.dataset_info())
print(dataset.feature_names)
print(dataset.target_names)
#print(dataset.train_set_targets)

minimize
hse_gap
192
(192, 4)
['organic', 'cation', 'anion']
['hse_gap']


In [114]:
df = dataset.descriptors
df.head()

param         option         name    value
0  organic  ethylammonium         homo  -0.4601
1  organic  ethylammonium         lumo -0.22398
2  organic  ethylammonium       dipole   1.3965
3  organic  ethylammonium  atomization -1.84142
4  organic  ethylammonium        r_gyr  1.26157

In [116]:
param_space = dataset.param_space

In [10]:
d = Dataset(name='snar', random_seed=42) # the seed makes the splits reproducible

In [4]:
# print data in Dataset
d.data

residence_time  ratio  concentration  temperature  e_factor
0             1.24   2.43          0.361         64.8      2.06
1             0.81   4.59          0.484         71.6      1.94
2             1.49   3.31          0.194         79.4      2.03
3             1.04   1.27          0.334         80.7      1.89
4             1.96   3.19          0.229         84.2      1.37
..             ...    ...            ...          ...       ...
61            0.50   2.49          0.500        139.6      0.78
62            0.50   3.01          0.500        140.0      0.95
63            0.50   2.76          0.500        140.0      0.86
64            0.50   3.28          0.500        140.0      1.03
65            1.12   1.00          0.500        140.0      0.30

[66 rows x 5 columns]

In [6]:
# print dataset info
d.dataset_info()

HPLC N9 dataset. Blablabla

                Summary
-----------------------------------------
    Number of Samples            1000
    Dimensionality                 13
    Features:
        Feat1              continuous
        Feat2              continuous
        Feat3             categorical
    Targets:
        Yield              continuous



In [8]:
# get names of features and targets
print(d.feature_names)
print(d.target_names)

['residence_time', 'ratio', 'concentration', 'temperature']
['e_factor']


In [11]:
# get data for features and targets

d.features
#d.targets

residence_time  ratio  concentration  temperature
0             1.24   2.43          0.361         64.8
1             0.81   4.59          0.484         71.6
2             1.49   3.31          0.194         79.4
3             1.04   1.27          0.334         80.7
4             1.96   3.19          0.229         84.2
..             ...    ...            ...          ...
61            0.50   2.49          0.500        139.6
62            0.50   3.01          0.500        140.0
63            0.50   2.76          0.500        140.0
64            0.50   3.28          0.500        140.0
65            1.12   1.00          0.500        140.0

[66 rows x 4 columns]

In [12]:
# customize splits
d = Dataset(name='snar', test_frac=0.3, num_folds=3, random_seed=42)

In [14]:
# show split indices
print(d.train_indices)
print()
print(d.test_indices)
print()
print(d.cv_fold_indices)

[ 1  2  4  6  7 10 11 14 15 18 19 20 21 22 23 24 26 27 28 29 31 32 35 36
 37 38 39 42 43 44 46 47 48 49 50 51 52 53 55 56 57 58 59 60 61 64]

[54 62  0 45  5 63 16 12 65 30 33  9 41 13 34 25  3 17 40  8]

[array([58, 19,  7, 48, 55,  4, 46, 64, 36, 20, 11, 60,  1, 32, 28, 29]), array([15, 37, 42, 59, 21, 52, 31, 39, 35, 47, 14, 23, 24, 61, 53]), array([44, 18, 49, 38, 27, 43, 57, 10,  2,  6, 56, 51, 26, 22, 50])]


In [20]:
# show data for the splits

# training set
d.train_set

# test set
#d.test_set

# CV sets
#d.cross_val_sets

residence_time  ratio  concentration  temperature  e_factor
1             0.81   4.59          0.484         71.6      1.94
2             1.49   3.31          0.194         79.4      2.03
4             1.96   3.19          0.229         84.2      1.37
6             1.66   4.75          0.214         92.2      1.76
7             1.74   3.43          0.425         97.1      1.08
10            0.59   3.70          0.388        111.6      1.35
11            1.17   3.84          0.400        115.2      1.23
14            1.92   4.96          0.313        124.8      1.68
15            0.88   1.12          0.295        132.0      0.63
18            0.50   4.09          0.500        111.0      1.48
19            0.97   1.00          0.500        140.0      0.33
20            0.50   1.34          0.500        140.0      0.52
21            0.64   1.00          0.500        140.0      0.44
22            2.00   1.00          0.500        129.1      0.25
23            0.50   2.29          0.500        137.8      0.72
24            0.81   1.07          0.500        140.0      0.36
26            0.50   2.89          0.500        140.0      0.91
27            0.50   1.78          0.500        140.0      0.60
28            0.60   1.19          0.500        140.0      0.46
29            0.69   1.00          0.500        140.0      0.42
31            1.02   1.19          0.499        126.7      0.40
32            0.75   1.43          0.500        129.7      0.47
35            0.77   1.33          0.500        140.0      0.39
36            1.52   1.09          0.500        140.0      0.25
37            0.50   2.00          0.500        140.0      0.63
38            0.92   1.22          0.500        139.9      0.36
39            0.50   4.51          0.500        140.0      1.50
42            0.50   3.19          0.500        140.0      1.01
43            0.50   2.58          0.500        140.0      0.80
44            1.05   1.00          0.500        140.0      0.31
46            1.88   1.00          0.425        134.5      0.30
47            1.73   1.00          0.460        137.9      0.26
48            1.60   1.00          0.490        139.8      0.26
49            0.53   1.23          0.500        140.0      0.49
50            0.50   4.70          0.500        140.0      1.57
51            0.50   1.60          0.500        140.0      0.56
52            0.62   1.00          0.499        140.0      0.46
53            0.92   1.00          0.500        140.0      0.34
55            0.70   1.37          0.500        140.0      0.42
56            1.62   1.00          0.500        140.0      0.24
57            0.93   1.13          0.500        140.0      0.32
58            1.26   1.00          0.500        134.1      0.32
59            1.41   1.00          0.500        134.2      0.29
60            0.50   2.20          0.500        139.4      0.69
61            0.50   2.49          0.500        139.6      0.78
64            0.50   3.28          0.500        140.0      1.03

In [22]:
# get only the features and targets for the training set

d.train_set_features
#d.train_set_targets


# you can do the same for test sets, and cv sets
# e.g.

#d.test_set_targets

residence_time  ratio  concentration  temperature
1             0.81   4.59          0.484         71.6
2             1.49   3.31          0.194         79.4
4             1.96   3.19          0.229         84.2
6             1.66   4.75          0.214         92.2
7             1.74   3.43          0.425         97.1
10            0.59   3.70          0.388        111.6
11            1.17   3.84          0.400        115.2
14            1.92   4.96          0.313        124.8
15            0.88   1.12          0.295        132.0
18            0.50   4.09          0.500        111.0
19            0.97   1.00          0.500        140.0
20            0.50   1.34          0.500        140.0
21            0.64   1.00          0.500        140.0
22            2.00   1.00          0.500        129.1
23            0.50   2.29          0.500        137.8
24            0.81   1.07          0.500        140.0
26            0.50   2.89          0.500        140.0
27            0.50   1.78          0.500        140.0
28            0.60   1.19          0.500        140.0
29            0.69   1.00          0.500        140.0
31            1.02   1.19          0.499        126.7
32            0.75   1.43          0.500        129.7
35            0.77   1.33          0.500        140.0
36            1.52   1.09          0.500        140.0
37            0.50   2.00          0.500        140.0
38            0.92   1.22          0.500        139.9
39            0.50   4.51          0.500        140.0
42            0.50   3.19          0.500        140.0
43            0.50   2.58          0.500        140.0
44            1.05   1.00          0.500        140.0
46            1.88   1.00          0.425        134.5
47            1.73   1.00          0.460        137.9
48            1.60   1.00          0.490        139.8
49            0.53   1.23          0.500        140.0
50            0.50   4.70          0.500        140.0
51            0.50   1.60          0.500        140.0
52            0.62   1.00          0.499        140.0
53            0.92   1.00          0.500        140.0
55            0.70   1.37          0.500        140.0
56            1.62   1.00          0.500        140.0
57            0.93   1.13          0.500        140.0
58            1.26   1.00          0.500        134.1
59            1.41   1.00          0.500        134.2
60            0.50   2.20          0.500        139.4
61            0.50   2.49          0.500        139.6
64            0.50   3.28          0.500        140.0

In [17]:
# access the data for each CV fold, with separate features and targets
for (train_feat, test_feat), (train_tar, test_tar) in zip(d.cross_val_sets_features,d.cross_val_sets_targets):
    print('='*100)
    print(test_feat)
    #print(test_feat)
    #print(train_tar)
    #print(test_tar)

    residence_time  ratio  concentration  temperature
51            0.50   1.60          0.500        140.0
55            0.70   1.37          0.500        140.0
6             1.66   4.75          0.214         92.2
53            0.92   1.00          0.500        140.0
46            1.88   1.00          0.425        134.5
23            0.50   2.29          0.500        137.8
38            0.92   1.22          0.500        139.9
15            0.88   1.12          0.295        132.0
3             1.04   1.27          0.334         80.7
14            1.92   4.96          0.313        124.8
28            0.60   1.19          0.500        140.0
    residence_time  ratio  concentration  temperature
59            1.41   1.00          0.500        134.2
36            1.52   1.09          0.500        140.0
57            0.93   1.13          0.500        140.0
8             1.27   1.73          0.111        103.9
24            0.81   1.07          0.500        140.0
1             0.81   4.59   

In [27]:
# return a pure numpy object, for any attribute that is a DataFrame (i.e. with data in it)
d.train_set.to_numpy()

array([[  0.81 ,   4.59 ,   0.484,  71.6  ,   1.94 ],
       [  1.49 ,   3.31 ,   0.194,  79.4  ,   2.03 ],
       [  1.96 ,   3.19 ,   0.229,  84.2  ,   1.37 ],
       [  1.66 ,   4.75 ,   0.214,  92.2  ,   1.76 ],
       [  1.74 ,   3.43 ,   0.425,  97.1  ,   1.08 ],
       [  0.59 ,   3.7  ,   0.388, 111.6  ,   1.35 ],
       [  1.17 ,   3.84 ,   0.4  , 115.2  ,   1.23 ],
       [  1.92 ,   4.96 ,   0.313, 124.8  ,   1.68 ],
       [  0.88 ,   1.12 ,   0.295, 132.   ,   0.63 ],
       [  0.5  ,   4.09 ,   0.5  , 111.   ,   1.48 ],
       [  0.97 ,   1.   ,   0.5  , 140.   ,   0.33 ],
       [  0.5  ,   1.34 ,   0.5  , 140.   ,   0.52 ],
       [  0.64 ,   1.   ,   0.5  , 140.   ,   0.44 ],
       [  2.   ,   1.   ,   0.5  , 129.1  ,   0.25 ],
       [  0.5  ,   2.29 ,   0.5  , 137.8  ,   0.72 ],
       [  0.81 ,   1.07 ,   0.5  , 140.   ,   0.36 ],
       [  0.5  ,   2.89 ,   0.5  , 140.   ,   0.91 ],
       [  0.5  ,   1.78 ,   0.5  , 140.   ,   0.6  ],
       [  0.6  ,   1.19 ,   

In [7]:
a = {'x0':[0,1,2], 'x1':[4,5,6]}
d = Dataset(data=a, target_ids=['x1'])
print(d.data)
print()
print(d.target_names)
print()
print(d.targets)

   x0  x1
0   0   4
1   1   5
2   2   6

['x1']

   x1
0   4
1   5
2   6


In [8]:
d.features

x0
0   0
1   1
2   2

In [22]:
d2 = d.cross_val_sets_features[0][1].to_numpy()
d2

array([[  0.5  ,   1.6  ,   0.5  , 140.   ],
       [  0.7  ,   1.37 ,   0.5  , 140.   ],
       [  1.66 ,   4.75 ,   0.214,  92.2  ],
       [  0.92 ,   1.   ,   0.5  , 140.   ],
       [  1.88 ,   1.   ,   0.425, 134.5  ],
       [  0.5  ,   2.29 ,   0.5  , 137.8  ],
       [  0.92 ,   1.22 ,   0.5  , 139.9  ],
       [  0.88 ,   1.12 ,   0.295, 132.   ],
       [  1.04 ,   1.27 ,   0.334,  80.7  ],
       [  1.92 ,   4.96 ,   0.313, 124.8  ],
       [  0.6  ,   1.19 ,   0.5  , 140.   ]])

In [25]:
from olympus.models.data_transformer import DataTransformer
t = DataTransformer(transformation='standardization')

t.train(d2)
t.transform(d2)

array([[-1.08267778, -0.27095465,  0.81640685,  0.62789231],
       [-0.6870148 , -0.4353468 ,  0.81640685,  0.62789231],
       [ 1.21216748,  1.98050306, -1.97838743, -1.76273605],
       [-0.25178553, -0.69980374,  0.81640685,  0.62789231],
       [ 1.64739675, -0.69980374,  0.08350625,  0.35282001],
       [-1.08267778,  0.2222218 ,  0.81640685,  0.51786339],
       [-0.25178553, -0.54255907,  0.81640685,  0.622891  ],
       [-0.33091812, -0.61403392, -1.18685479,  0.22778715],
       [-0.01438774, -0.50682165, -0.80574647, -2.33788723],
       [ 1.72652935,  2.13060024, -1.01095864, -0.1323075 ],
       [-0.88484629, -0.56400153,  0.81640685,  0.62789231]])